name: .NET Core

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download Everest stripped lib
      uses: robinraju/release-downloader@v1.4
      with:
        repository: EverestAPI/Everest
        latest: true
        fileName: lib-stripped.zip

    - name: Extract lib-stripped.zip
      run: unzip lib-stripped.zip

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build RainTools.csproj /property:DefineConstants=FROSTHELPER_BLENDSTATE_COMPAT --configuration Release --no-restore
      env:
        CelestePrefix: ${{ github.workspace }}/lib-stripped

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: RainTools_${{ github.ref_name }}
        path: |
          everest.yaml
          bin/RainTools.*
          Loenn
          Graphics
        if-no-files-found: error
        
    - name: Zip Mod
      run: zip RainTools_${{ github.ref_name }}.zip -r everest.yaml bin/RainTools.* Loenn Graphics

    - name: Upload Result
      uses: sinshutu/upload-to-discord@v2.0.0
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: RainTools_${{ github.ref_name }}.zip
